//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALENDAR
    {
        public int eventID { get; set; }
        public string eventHeader { get; set; }
        public string eventDescription { get; set; }
        public Nullable<System.DateTime> eventStart { get; set; }
        public Nullable<System.DateTime> eventEnd { get; set; }
    }
}
